[[redirects]]
  from = "/proxy/*"
  to = "https://api.suwiki.kr/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  AWS_API_URL = "From netlify.toml (AWS_API_URL)"