export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as Write } from './Write'
export { default as NoticeDetail } from './NoticeDetail'
export { default as Update } from './Update'